"""Summarizes the JSON-lines results of synthetic_direct into markdown tables.

Usage: python3 summarize.py RESULTS_DIR

Reads keys.jsonl (or keys.jsonl.gz) and crosscheck.json when present, and
writes summary.md and summary.json to the same directory. Uses only the
Python standard library.
"""

import collections
import gzip
import json
import os
import statistics
import sys


def load(path):
    if os.path.exists(path):
        f = open(path)
    elif os.path.exists(path + ".gz"):
        f = gzip.open(path + ".gz", "rt")
    else:
        return []
    with f:
        return [json.loads(line) for line in f if line.strip()]


def span(values):
    vs = sorted(set(values))
    return str(vs[0]) if len(vs) == 1 else "%d-%d" % (vs[0], vs[-1])


def main():
    d = sys.argv[1] if len(sys.argv) > 1 else "results"
    rows = load(os.path.join(d, "keys.jsonl"))
    groups = collections.OrderedDict()
    order = {"binary-goppa": 0, "wild-goppa": 1, "alternant": 2}
    for r in sorted(rows, key=lambda r: (r["label"].startswith("control"), order[r["family"]],
                                         r["q"], r["n"], r["label"])):
        groups.setdefault(r["label"], []).append(r)

    checks = collections.Counter()
    for r in rows:
        checks["curve_failed"] += not r["checks"]["curve"]
        checks["jet_not_at_public_column"] += not r["checks"]["jet_starts_at_public_column"]
        checks["verified_but_audit_failed"] += r["equal"] and not r["audit"]

    md = ["# Summary of results", "",
          "Generated by `summarize.py` from `keys.jsonl.gz`. One jet per key, at a random",
          "position, with a random reparametrization and a random Frobenius branch.", "",
          "## Recovery", "",
          "| Set | Family | q | m | n | k | D | Forms | Jet order | Keys | R found | S found | Recovered | Median s |",
          "|---|---|---:|---:|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|"]
    summary = {"keys": len(rows), "checks": dict(checks), "sets": []}
    failures = collections.Counter()
    for label, rs in groups.items():
        r0 = rs[0]
        forms = ("degree %s, " % span(r["delta"] for r in rs)) + (
            "orders 2D, 2D-2, square root" if r0["variant"] == "square-root" else "adjacent orders")
        rec = sum(r["success"] for r in rs)
        for r in rs:
            if not r["success"]:
                failures[(label, r["failure"] or "audit")] += 1
        md.append("| `%s` | %s | %d | %d | %d | %s | %s | %s | %s | %d | %d | %d | %d | %.2f |"
                  % (label, r0["family"], r0["q"], r0["m"], r0["n"], span(r["k"] for r in rs),
                     span(r["D"] for r in rs), forms, span(r["jet_order"] for r in rs), len(rs),
                     sum(r["R_found"] for r in rs), sum(r["S_found"] for r in rs), rec,
                     statistics.median(r["seconds"]["total"] for r in rs)))
        summary["sets"].append({"label": label, "keys": len(rs), "recovered": rec,
                                "R_found": sum(r["R_found"] for r in rs),
                                "S_found": sum(r["S_found"] for r in rs)})
    md += ["", "## Failures", ""]
    if failures:
        md += ["| Set | Reason | Keys |", "|---|---|---:|"]
        md += ["| `%s` | %s | %d |" % (k[0], k[1], v) for k, v in sorted(failures.items())]
    else:
        md.append("None.")
    summary["failures"] = {"%s: %s" % k: v for k, v in failures.items()}
    md += ["", "## Consistency checks", "",
           "Counts of keys failing a check (all should be zero).", "",
           "| Check | Keys |", "|---|---:|"]
    md += ["| %s | %d |" % (k, checks[k]) for k in
           ("curve_failed", "jet_not_at_public_column", "verified_but_audit_failed")]
    cc_path = os.path.join(d, "crosscheck.json")
    if os.path.exists(cc_path):
        with open(cc_path) as f:
            cc = json.load(f)
        summary["crosscheck"] = {"keys": cc["keys"], "all_ok": cc["all_ok"]}
        md += ["", "## SageMath cross-check", "",
               "%d recovered keys rechecked independently: %s." % (cc["keys"], "all pass" if cc["all_ok"] else "MISMATCH")]
    with open(os.path.join(d, "summary.md"), "w") as f:
        f.write("\n".join(md) + "\n")
    with open(os.path.join(d, "summary.json"), "w") as f:
        json.dump(summary, f, indent=1)
    print("\n".join(md))


if __name__ == "__main__":
    main()
